
JOIN_ROOM = 'JOIN_ROOM'
CHAT_MESSAGE = 'CHAT_MESSAGE'
LEAVE_ROOM = 'LEAVE_ROOM'
FINISHED_ONBOARDING = 'FINISHED_ONBOARDING'

WASON_INITIAL = 'WASON_INITIAL'
WASON_GAME = 'WASON_GAME'
WASON_AGREE = 'WASON_SUBMIT'
WASON_FINISHED = 'WASON_FINISHED'

USR_ONBOARDING = 'USR_ONBOARDING'
USR_PLAYING = 'USR_PLAYING'
USR_MODERATING = 'USR_MODERATING'