
JOIN_ROOM = 'JOIN_ROOM'
CHAT_MESSAGE = 'CHAT_MESSAGE'
LEAVE_ROOM = 'LEAVE_ROOM'

WASON_INITIAL = 'WASON_INITIAL'
WASON_GAME = 'WASON_GAME'
WASON_AGREE = 'WASON_SUBMIT'
WASON_FINISHED = 'WASON_FINISHED'